/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AppRouteImport } from './routes/app'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsWebsearchRouteImport } from './routes/settings/websearch'
import { Route as SettingsUsageRouteImport } from './routes/settings/usage'
import { Route as SettingsSystemRouteImport } from './routes/settings/system'
import { Route as SettingsShortcutRouteImport } from './routes/settings/shortcut'
import { Route as SettingsSelectionAssistantRouteImport } from './routes/settings/selection-assistant'
import { Route as SettingsQuickAssistantRouteImport } from './routes/settings/quick-assistant'
import { Route as SettingsProviderRouteImport } from './routes/settings/provider'
import { Route as SettingsOcrRouteImport } from './routes/settings/ocr'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsModelRouteImport } from './routes/settings/model'
import { Route as SettingsMcpRouteImport } from './routes/settings/mcp'
import { Route as SettingsFileProcessingRouteImport } from './routes/settings/file-processing'
import { Route as SettingsDependenciesRouteImport } from './routes/settings/dependencies'
import { Route as SettingsDataRouteImport } from './routes/settings/data'
import { Route as SettingsCodeExecutionRouteImport } from './routes/settings/code-execution'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as AppTranslateRouteImport } from './routes/app/translate'
import { Route as AppLaunchpadRouteImport } from './routes/app/launchpad'
import { Route as AppFilePreviewRouteImport } from './routes/app/file-preview'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as SettingsMcpIndexRouteImport } from './routes/settings/mcp.index'
import { Route as SettingsMcpServersRouteImport } from './routes/settings/mcp/servers'
import { Route as SettingsMcpNpxSearchRouteImport } from './routes/settings/mcp/npx-search'
import { Route as SettingsMcpMcpInstallRouteImport } from './routes/settings/mcp/mcp-install'
import { Route as SettingsMcpMarketplacesRouteImport } from './routes/settings/mcp/marketplaces'
import { Route as SettingsMcpBuiltinRouteImport } from './routes/settings/mcp/builtin'
import { Route as SettingsMcpSplatRouteImport } from './routes/settings/mcp/$'
import { Route as SettingsMcpSettingsServerIdRouteImport } from './routes/settings/mcp/settings.$serverId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsWebsearchRoute = SettingsWebsearchRouteImport.update({
  id: '/websearch',
  path: '/websearch',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsageRoute = SettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsShortcutRoute = SettingsShortcutRouteImport.update({
  id: '/shortcut',
  path: '/shortcut',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSelectionAssistantRoute =
  SettingsSelectionAssistantRouteImport.update({
    id: '/selection-assistant',
    path: '/selection-assistant',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsQuickAssistantRoute = SettingsQuickAssistantRouteImport.update({
  id: '/quick-assistant',
  path: '/quick-assistant',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProviderRoute = SettingsProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsOcrRoute = SettingsOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelRoute = SettingsModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMcpRoute = SettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFileProcessingRoute = SettingsFileProcessingRouteImport.update({
  id: '/file-processing',
  path: '/file-processing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDependenciesRoute = SettingsDependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCodeExecutionRoute = SettingsCodeExecutionRouteImport.update({
  id: '/code-execution',
  path: '/code-execution',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const AppTranslateRoute = AppTranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => AppRoute,
} as any)
const AppLaunchpadRoute = AppLaunchpadRouteImport.update({
  id: '/launchpad',
  path: '/launchpad',
  getParentRoute: () => AppRoute,
} as any)
const AppFilePreviewRoute = AppFilePreviewRouteImport.update({
  id: '/file-preview',
  path: '/file-preview',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const SettingsMcpIndexRoute = SettingsMcpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpServersRoute = SettingsMcpServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpNpxSearchRoute = SettingsMcpNpxSearchRouteImport.update({
  id: '/npx-search',
  path: '/npx-search',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpMcpInstallRoute = SettingsMcpMcpInstallRouteImport.update({
  id: '/mcp-install',
  path: '/mcp-install',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpMarketplacesRoute = SettingsMcpMarketplacesRouteImport.update({
  id: '/marketplaces',
  path: '/marketplaces',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpBuiltinRoute = SettingsMcpBuiltinRouteImport.update({
  id: '/builtin',
  path: '/builtin',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpSplatRoute = SettingsMcpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SettingsMcpRoute,
} as any)
const SettingsMcpSettingsServerIdRoute =
  SettingsMcpSettingsServerIdRouteImport.update({
    id: '/settings/$serverId',
    path: '/settings/$serverId',
    getParentRoute: () => SettingsMcpRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/app/chat': typeof AppChatRoute
  '/app/file-preview': typeof AppFilePreviewRoute
  '/app/launchpad': typeof AppLaunchpadRoute
  '/app/translate': typeof AppTranslateRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/code-execution': typeof SettingsCodeExecutionRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/dependencies': typeof SettingsDependenciesRoute
  '/settings/file-processing': typeof SettingsFileProcessingRoute
  '/settings/mcp': typeof SettingsMcpRouteWithChildren
  '/settings/model': typeof SettingsModelRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/ocr': typeof SettingsOcrRoute
  '/settings/provider': typeof SettingsProviderRoute
  '/settings/quick-assistant': typeof SettingsQuickAssistantRoute
  '/settings/selection-assistant': typeof SettingsSelectionAssistantRoute
  '/settings/shortcut': typeof SettingsShortcutRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/settings/websearch': typeof SettingsWebsearchRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/mcp/$': typeof SettingsMcpSplatRoute
  '/settings/mcp/builtin': typeof SettingsMcpBuiltinRoute
  '/settings/mcp/marketplaces': typeof SettingsMcpMarketplacesRoute
  '/settings/mcp/mcp-install': typeof SettingsMcpMcpInstallRoute
  '/settings/mcp/npx-search': typeof SettingsMcpNpxSearchRoute
  '/settings/mcp/servers': typeof SettingsMcpServersRoute
  '/settings/mcp/': typeof SettingsMcpIndexRoute
  '/settings/mcp/settings/$serverId': typeof SettingsMcpSettingsServerIdRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteWithChildren
  '/app/chat': typeof AppChatRoute
  '/app/file-preview': typeof AppFilePreviewRoute
  '/app/launchpad': typeof AppLaunchpadRoute
  '/app/translate': typeof AppTranslateRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/code-execution': typeof SettingsCodeExecutionRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/dependencies': typeof SettingsDependenciesRoute
  '/settings/file-processing': typeof SettingsFileProcessingRoute
  '/settings/model': typeof SettingsModelRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/ocr': typeof SettingsOcrRoute
  '/settings/provider': typeof SettingsProviderRoute
  '/settings/quick-assistant': typeof SettingsQuickAssistantRoute
  '/settings/selection-assistant': typeof SettingsSelectionAssistantRoute
  '/settings/shortcut': typeof SettingsShortcutRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/settings/websearch': typeof SettingsWebsearchRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/mcp/$': typeof SettingsMcpSplatRoute
  '/settings/mcp/builtin': typeof SettingsMcpBuiltinRoute
  '/settings/mcp/marketplaces': typeof SettingsMcpMarketplacesRoute
  '/settings/mcp/mcp-install': typeof SettingsMcpMcpInstallRoute
  '/settings/mcp/npx-search': typeof SettingsMcpNpxSearchRoute
  '/settings/mcp/servers': typeof SettingsMcpServersRoute
  '/settings/mcp': typeof SettingsMcpIndexRoute
  '/settings/mcp/settings/$serverId': typeof SettingsMcpSettingsServerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/app/chat': typeof AppChatRoute
  '/app/file-preview': typeof AppFilePreviewRoute
  '/app/launchpad': typeof AppLaunchpadRoute
  '/app/translate': typeof AppTranslateRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/code-execution': typeof SettingsCodeExecutionRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/dependencies': typeof SettingsDependenciesRoute
  '/settings/file-processing': typeof SettingsFileProcessingRoute
  '/settings/mcp': typeof SettingsMcpRouteWithChildren
  '/settings/model': typeof SettingsModelRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/ocr': typeof SettingsOcrRoute
  '/settings/provider': typeof SettingsProviderRoute
  '/settings/quick-assistant': typeof SettingsQuickAssistantRoute
  '/settings/selection-assistant': typeof SettingsSelectionAssistantRoute
  '/settings/shortcut': typeof SettingsShortcutRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/settings/websearch': typeof SettingsWebsearchRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/mcp/$': typeof SettingsMcpSplatRoute
  '/settings/mcp/builtin': typeof SettingsMcpBuiltinRoute
  '/settings/mcp/marketplaces': typeof SettingsMcpMarketplacesRoute
  '/settings/mcp/mcp-install': typeof SettingsMcpMcpInstallRoute
  '/settings/mcp/npx-search': typeof SettingsMcpNpxSearchRoute
  '/settings/mcp/servers': typeof SettingsMcpServersRoute
  '/settings/mcp/': typeof SettingsMcpIndexRoute
  '/settings/mcp/settings/$serverId': typeof SettingsMcpSettingsServerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/settings'
    | '/app/chat'
    | '/app/file-preview'
    | '/app/launchpad'
    | '/app/translate'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/code-execution'
    | '/settings/data'
    | '/settings/dependencies'
    | '/settings/file-processing'
    | '/settings/mcp'
    | '/settings/model'
    | '/settings/notifications'
    | '/settings/ocr'
    | '/settings/provider'
    | '/settings/quick-assistant'
    | '/settings/selection-assistant'
    | '/settings/shortcut'
    | '/settings/system'
    | '/settings/usage'
    | '/settings/websearch'
    | '/settings/'
    | '/settings/mcp/$'
    | '/settings/mcp/builtin'
    | '/settings/mcp/marketplaces'
    | '/settings/mcp/mcp-install'
    | '/settings/mcp/npx-search'
    | '/settings/mcp/servers'
    | '/settings/mcp/'
    | '/settings/mcp/settings/$serverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/app/chat'
    | '/app/file-preview'
    | '/app/launchpad'
    | '/app/translate'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/code-execution'
    | '/settings/data'
    | '/settings/dependencies'
    | '/settings/file-processing'
    | '/settings/model'
    | '/settings/notifications'
    | '/settings/ocr'
    | '/settings/provider'
    | '/settings/quick-assistant'
    | '/settings/selection-assistant'
    | '/settings/shortcut'
    | '/settings/system'
    | '/settings/usage'
    | '/settings/websearch'
    | '/settings'
    | '/settings/mcp/$'
    | '/settings/mcp/builtin'
    | '/settings/mcp/marketplaces'
    | '/settings/mcp/mcp-install'
    | '/settings/mcp/npx-search'
    | '/settings/mcp/servers'
    | '/settings/mcp'
    | '/settings/mcp/settings/$serverId'
  id:
    | '__root__'
    | '/app'
    | '/settings'
    | '/app/chat'
    | '/app/file-preview'
    | '/app/launchpad'
    | '/app/translate'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/code-execution'
    | '/settings/data'
    | '/settings/dependencies'
    | '/settings/file-processing'
    | '/settings/mcp'
    | '/settings/model'
    | '/settings/notifications'
    | '/settings/ocr'
    | '/settings/provider'
    | '/settings/quick-assistant'
    | '/settings/selection-assistant'
    | '/settings/shortcut'
    | '/settings/system'
    | '/settings/usage'
    | '/settings/websearch'
    | '/settings/'
    | '/settings/mcp/$'
    | '/settings/mcp/builtin'
    | '/settings/mcp/marketplaces'
    | '/settings/mcp/mcp-install'
    | '/settings/mcp/npx-search'
    | '/settings/mcp/servers'
    | '/settings/mcp/'
    | '/settings/mcp/settings/$serverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/websearch': {
      id: '/settings/websearch'
      path: '/websearch'
      fullPath: '/settings/websearch'
      preLoaderRoute: typeof SettingsWebsearchRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/usage': {
      id: '/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SettingsUsageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/shortcut': {
      id: '/settings/shortcut'
      path: '/shortcut'
      fullPath: '/settings/shortcut'
      preLoaderRoute: typeof SettingsShortcutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/selection-assistant': {
      id: '/settings/selection-assistant'
      path: '/selection-assistant'
      fullPath: '/settings/selection-assistant'
      preLoaderRoute: typeof SettingsSelectionAssistantRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/quick-assistant': {
      id: '/settings/quick-assistant'
      path: '/quick-assistant'
      fullPath: '/settings/quick-assistant'
      preLoaderRoute: typeof SettingsQuickAssistantRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/provider': {
      id: '/settings/provider'
      path: '/provider'
      fullPath: '/settings/provider'
      preLoaderRoute: typeof SettingsProviderRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/ocr': {
      id: '/settings/ocr'
      path: '/ocr'
      fullPath: '/settings/ocr'
      preLoaderRoute: typeof SettingsOcrRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/model': {
      id: '/settings/model'
      path: '/model'
      fullPath: '/settings/model'
      preLoaderRoute: typeof SettingsModelRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/file-processing': {
      id: '/settings/file-processing'
      path: '/file-processing'
      fullPath: '/settings/file-processing'
      preLoaderRoute: typeof SettingsFileProcessingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/dependencies': {
      id: '/settings/dependencies'
      path: '/dependencies'
      fullPath: '/settings/dependencies'
      preLoaderRoute: typeof SettingsDependenciesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/code-execution': {
      id: '/settings/code-execution'
      path: '/code-execution'
      fullPath: '/settings/code-execution'
      preLoaderRoute: typeof SettingsCodeExecutionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/app/translate': {
      id: '/app/translate'
      path: '/translate'
      fullPath: '/app/translate'
      preLoaderRoute: typeof AppTranslateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/launchpad': {
      id: '/app/launchpad'
      path: '/launchpad'
      fullPath: '/app/launchpad'
      preLoaderRoute: typeof AppLaunchpadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/file-preview': {
      id: '/app/file-preview'
      path: '/file-preview'
      fullPath: '/app/file-preview'
      preLoaderRoute: typeof AppFilePreviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/settings/mcp/': {
      id: '/settings/mcp/'
      path: '/'
      fullPath: '/settings/mcp/'
      preLoaderRoute: typeof SettingsMcpIndexRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/servers': {
      id: '/settings/mcp/servers'
      path: '/servers'
      fullPath: '/settings/mcp/servers'
      preLoaderRoute: typeof SettingsMcpServersRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/npx-search': {
      id: '/settings/mcp/npx-search'
      path: '/npx-search'
      fullPath: '/settings/mcp/npx-search'
      preLoaderRoute: typeof SettingsMcpNpxSearchRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/mcp-install': {
      id: '/settings/mcp/mcp-install'
      path: '/mcp-install'
      fullPath: '/settings/mcp/mcp-install'
      preLoaderRoute: typeof SettingsMcpMcpInstallRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/marketplaces': {
      id: '/settings/mcp/marketplaces'
      path: '/marketplaces'
      fullPath: '/settings/mcp/marketplaces'
      preLoaderRoute: typeof SettingsMcpMarketplacesRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/builtin': {
      id: '/settings/mcp/builtin'
      path: '/builtin'
      fullPath: '/settings/mcp/builtin'
      preLoaderRoute: typeof SettingsMcpBuiltinRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/$': {
      id: '/settings/mcp/$'
      path: '/$'
      fullPath: '/settings/mcp/$'
      preLoaderRoute: typeof SettingsMcpSplatRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
    '/settings/mcp/settings/$serverId': {
      id: '/settings/mcp/settings/$serverId'
      path: '/settings/$serverId'
      fullPath: '/settings/mcp/settings/$serverId'
      preLoaderRoute: typeof SettingsMcpSettingsServerIdRouteImport
      parentRoute: typeof SettingsMcpRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppFilePreviewRoute: typeof AppFilePreviewRoute
  AppLaunchpadRoute: typeof AppLaunchpadRoute
  AppTranslateRoute: typeof AppTranslateRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppFilePreviewRoute: AppFilePreviewRoute,
  AppLaunchpadRoute: AppLaunchpadRoute,
  AppTranslateRoute: AppTranslateRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SettingsMcpRouteChildren {
  SettingsMcpSplatRoute: typeof SettingsMcpSplatRoute
  SettingsMcpBuiltinRoute: typeof SettingsMcpBuiltinRoute
  SettingsMcpMarketplacesRoute: typeof SettingsMcpMarketplacesRoute
  SettingsMcpMcpInstallRoute: typeof SettingsMcpMcpInstallRoute
  SettingsMcpNpxSearchRoute: typeof SettingsMcpNpxSearchRoute
  SettingsMcpServersRoute: typeof SettingsMcpServersRoute
  SettingsMcpIndexRoute: typeof SettingsMcpIndexRoute
  SettingsMcpSettingsServerIdRoute: typeof SettingsMcpSettingsServerIdRoute
}

const SettingsMcpRouteChildren: SettingsMcpRouteChildren = {
  SettingsMcpSplatRoute: SettingsMcpSplatRoute,
  SettingsMcpBuiltinRoute: SettingsMcpBuiltinRoute,
  SettingsMcpMarketplacesRoute: SettingsMcpMarketplacesRoute,
  SettingsMcpMcpInstallRoute: SettingsMcpMcpInstallRoute,
  SettingsMcpNpxSearchRoute: SettingsMcpNpxSearchRoute,
  SettingsMcpServersRoute: SettingsMcpServersRoute,
  SettingsMcpIndexRoute: SettingsMcpIndexRoute,
  SettingsMcpSettingsServerIdRoute: SettingsMcpSettingsServerIdRoute,
}

const SettingsMcpRouteWithChildren = SettingsMcpRoute._addFileChildren(
  SettingsMcpRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsCodeExecutionRoute: typeof SettingsCodeExecutionRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsDependenciesRoute: typeof SettingsDependenciesRoute
  SettingsFileProcessingRoute: typeof SettingsFileProcessingRoute
  SettingsMcpRoute: typeof SettingsMcpRouteWithChildren
  SettingsModelRoute: typeof SettingsModelRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsOcrRoute: typeof SettingsOcrRoute
  SettingsProviderRoute: typeof SettingsProviderRoute
  SettingsQuickAssistantRoute: typeof SettingsQuickAssistantRoute
  SettingsSelectionAssistantRoute: typeof SettingsSelectionAssistantRoute
  SettingsShortcutRoute: typeof SettingsShortcutRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
  SettingsUsageRoute: typeof SettingsUsageRoute
  SettingsWebsearchRoute: typeof SettingsWebsearchRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsCodeExecutionRoute: SettingsCodeExecutionRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsDependenciesRoute: SettingsDependenciesRoute,
  SettingsFileProcessingRoute: SettingsFileProcessingRoute,
  SettingsMcpRoute: SettingsMcpRouteWithChildren,
  SettingsModelRoute: SettingsModelRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsOcrRoute: SettingsOcrRoute,
  SettingsProviderRoute: SettingsProviderRoute,
  SettingsQuickAssistantRoute: SettingsQuickAssistantRoute,
  SettingsSelectionAssistantRoute: SettingsSelectionAssistantRoute,
  SettingsShortcutRoute: SettingsShortcutRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsUsageRoute: SettingsUsageRoute,
  SettingsWebsearchRoute: SettingsWebsearchRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
